### ISSUE TITLE
Not Compatible with Layer 0.14

### ISSUE THREAD

**Issue by sambarboza** [layerhq/Atlas-Android#10]
Hello, 

In my project I am using Layer 0.14 and Atlas uses 0.13, because of it, it was crashing my app.
I have changed the version in Atlas build.gradle file, commented lines 210~219 in AtlasMessageList (it seems to be support to receipt view).

The line causing the crash before was line 226 in the same file:
```java
if (!msg.getSender().getUserId().equals(client.getAuthenticatedUserId())) {
```
I think the return method of Message#getSender() changed from 0.13 to 0.14.

I would like to know if pull-requests are encouraged for this library and if there is someone already working on this issue.

Thanks and sorry for any english mistakes (still learning it).

**Comment by sjones94549** [comment]
PRs are welcome; master is now based on SDK 0.16.0
