### ISSUE TITLE
Failed to reslove adding in gradle

### ISSUE THREAD

**Issue by adilp** [layerhq/Atlas-Android#101]
I have tried to add the library in gradle
compile 'com.layer.atlas:layer-atlas:0.2.10'

And I get this error 

Error:(42, 13) Failed to resolve: com.layer.atlas:layer-atlas:0.2.10

**Comment by josealfonsomora** [comment]
Hi @adilp ,

did you add the repository?

```java
allprojects {
    repositories {
        maven { url "https://raw.githubusercontent.com/layerhq/releases-android/master/releases/" }
        maven { url "https://raw.githubusercontent.com/layerhq/Atlas-Android/master/releases/" }
        jcenter()
        mavenCentral()
    }
}
```
That should fix the problem

**Comment by andela-wakinsanmi** [comment]
Thanks @josealfonsomora
