### ISSUE TITLE
Provide an extensible way to determine last message preview text

### ISSUE THREAD

**Issue by sriamar** [layerhq/Atlas-Android#102]
`AtlasConversationsAdapter` is using `Util.getLastMessageString` to set `viewholder.mMessageView` and it doesn’t support any overriding and supports only default message types.

**Comment by cpiggott** [comment]
Any update on this @sriamar ?

**Comment by cpiggott** [comment]
Any update or solution for this?

**Comment by sriamar** [comment]
Hi @cpiggott 

Sorry, missed this. This is fixed. Each cell factory now implements and provides Preview text via `getPreviewText`. Please take a look at the PR that did this for more details
https://github.com/layerhq/Atlas-Android/pull/124

Thanks,
Amar
