### ISSUE TITLE
android nougat

### ISSUE THREAD

**Issue by kalvish21** [layerhq/Atlas-Android#103]
We are having issues with android nougat where users can't sometimes see the conversations, the messages are never sent/received to the device (the push notifications are). We are using the below versions:

```
compile ('com.layer.sdk:layer-sdk:0.21.3')
compile ('com.layer.atlas:layer-atlas:0.2.14')
```

Is there something missing here?

**Comment by kraghu** [comment]
Is it fixed ?

**Comment by kenzo23312** [comment]
Same problem is there any fix?

**Comment by andela-wakinsanmi** [comment]
Hello @kalvish21 @kraghu @kenzo23312 

Can you please follow the steps here (https://docs.layer.com/sdk/android/support) to provide logs, this is an sdk issue and we use a different system to track the ticket. After submitting the log, you will get a ticket id to reference.

Thanks.
