### ISSUE TITLE
How to keep track of unread conversation count?

### ISSUE THREAD

**Issue by kkgelu** [layerhq/Atlas-Android#104]
I used this query to get the unread conversation count

``` java
Query query = Query.builder(Conversation.class)
                    .predicate(new Predicate(Conversation.Property.HAS_UNREAD_MESSAGES, Predicate.Operator.EQUAL_TO, true))
                    .build();

Long unreadCount = layerClient.executeQueryForCount(query);
```

Seems to work.  Question is how do I keep trace of the count change?

The iOS version has the query controller concept:

``` objective-c
- (nullable LYRQueryController *)queryControllerWithQuery:(nonnull LYRQuery *)query error:(NSError * _Nullable * _Nullable)error;
```

I found the `LayerChangeEventListener` and implemented

``` Java
public void onChangeEvent(LayerChangeEvent event) {
        boolean conversationUpdated = false;
        List<LayerChange> changes = event.getChanges();
        for (LayerChange change : changes) {
            if(change.getObjectType() == LayerObject.Type.CONVERSATION){

                conversationUpdated = true;
                break;
            }
        }
        if(conversationUpdated){
            updateUnreadConversationCount();
        }

```

The problem is this event is fired too often! `updateUnreadConversationCount` is called a lot than needed.

Any suggestions on how to do this efficiently?

**Comment by sriamar** [comment]
Hi @kkgelu ,

For questions on Layer Android SDK, please contact Layer Support via https://support.layer.com/hc/en-us. 

In this particular case, you can filter the changes using the `LayerChange.Type` and `AttributeName`. 

Unread count will be affected by the following
1. `Type` ==  `Insert` and `LayerObject` == `Conversation`
2. `Type` ==  `Delete` and `LayerObject` == `Conversation`
3. `Type` == `Update` and `LayerObject` == `Conversation and `getAttributeName` == `totalUnreadMessageCount`

Hope this helps. Please contact support if you have any further questions using the instructions above.

Thanks
Amar
