### ISSUE TITLE
AtlasMessagesRecyclerView loads with only one message

### ISSUE THREAD

**Issue by alistairsykes** [layerhq/Atlas-Android#105]
When opening a conversation for the first time, it only loads with the latest message. If you drag down it then loads the rest of them. I was under the impression that having `AtlasHistoricMessagesFetchLayout` as the parent view would mean it would load with `mSyncAmount` of messages. Could you offer any insight into this, i.e. how are you expecting it to behave and have I implemented something wrong.

**Comment by andela-wakinsanmi** [comment]
Hello @alistairsykes 

Thanks for reaching out, you need to set `setInitialHistoricMessagesToFetch(20)` on your AtlasConversationRecyclerView initialization. This is how we are doing it in Atlas Messenger  https://github.com/layerhq/Atlas-Android-Messenger/blob/master/app/src/main/java/com/layer/messenger/ConversationsListActivity.java#L41
