### ISSUE TITLE
Major lag for moderately large conversations.

### ISSUE THREAD

**Issue by reubenjohn** [layerhq/Atlas-Android#11]
Using Android method tracking I've come to conclude that the use of: LayerClient.getMessages(Conversation conversation) causes major lags in the context: 
`com.layer.atlas.AtlasMessagesList` -> `init()` -> `updateValues()` -> `List<Message> messages = client.getMessages(conv);` can cause major lags of the order of more than 5000ms on the main thread and in some cases even memory allocation failures.

A suggesstion as backed by the [Layer android api documentation](https://developer.layer.com/docs/android/api) would be to use an implementation using getConversationIds() instead of getMessages():
> List getConversationIds()
> Returns a list of all Conversation IDs. Conversation objects can then be loaded by ID with either the getConversation(id) or getConversations(ids) methods. Such a combination can be used to implement a lazy loading mechanism, such as an Adapter for a Conversation ListView. The Adapter can be made dynamic by implementing a LayerChangeEventListener interface.

**Comment by rockerhieu** [comment]
The lag is noticeable for conversation whose only a few messages also. I suggest that Atlas support support pagination for `AtlasMessagesList`.

**Comment by sjones94549** [comment]
we're moving all this to the background thread and generally improving performance shortly; the main SDK has RecyclerViewController/ListViewControllers that drive their respective Adapters off the main thread.  We will bring those into Atlas as the best practice as well.
