### ISSUE TITLE
Update getLastMessageString to pull from registered factories

### ISSUE THREAD

**Issue by cpiggott** [layerhq/Atlas-Android#111]
Any chance we can get an update on this? 

Specifically: [Util.java](https://github.com/layerhq/Atlas-Android/blob/6501626c03b699513ac0778cfd4ba03643d13094/layer-atlas/src/main/java/com/layer/atlas/util/Util.java#L75)

Looking to release an application into production soon, and hate having to display [xxx-byte mime/type] to my users in the message preview. 

If not, any insight into a quick fix, I don't mind working on this and fixing it, but would appreciate some help as to where to grab the registered factories.

**Comment by andela-wakinsanmi** [comment]
Hello @cpiggott 

Thanks for reaching out, I believe this has been fixed https://github.com/layerhq/Atlas-Android/pull/124/files#diff-155b18efd60244c07dfb375d90c6d5ffR121

Thanks
