### ISSUE TITLE
Got 401 when login

### ISSUE THREAD

**Issue by jimxj** [layerhq/Atlas-Android#12]
I can login the web site with my account. But got this error in the layer-atlas-message app.

07-10 19:47:47.728    8137-8167/com.layer.atlas.messenger D/﹕ HostConnection::get() New Host Connection established 0xafb0b770, tid 8167
07-10 19:47:47.741    8137-8167/com.layer.atlas.messenger I/OpenGLRenderer﹕ Initialized EGL, version 1.4
07-10 19:47:47.769    8137-8167/com.layer.atlas.messenger D/OpenGLRenderer﹕ Enabling debug mode 0
07-10 19:47:47.780    8137-8167/com.layer.atlas.messenger W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-10 19:47:47.780    8137-8167/com.layer.atlas.messenger W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xafb08f20, error=EGL_SUCCESS
07-10 19:47:47.975    8137-8164/com.layer.atlas.messenger V/LayerSDK﹕ LayerClientImpl - 2015-07-10T19:47:47.975 EDT : com.layer.sdk.internal.LayerClientImpl.o(LayerClientImpl.java:2037) : Connected, informing 0 listeners
07-10 19:47:48.030    8137-8186/com.layer.atlas.messenger V/LayerSDK﹕ LayerClientImpl - 2015-07-10T19:47:48.030 EDT : com.layer.sdk.internal.LayerClientImpl.a(LayerClientImpl.java:1139) : Authentication challenge, nonce length: 88
07-10 19:47:50.552    8137-8137/com.layer.atlas.messenger V/LayerSDK﹕ LayerClientImpl - 2015-07-10T19:47:50.552 EDT : com.layer.sdk.internal.LayerClientImpl.unregisterEventListener(LayerClientImpl.java:1767) : Unregistering LayerChangeEventListener, no remaining listeners
07-10 19:47:50.589    8137-8167/com.layer.atlas.messenger W/EGL_emulation﹕ eglSurfaceAttrib not implemented
07-10 19:47:50.589    8137-8167/com.layer.atlas.messenger W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xafb34080, error=EGL_SUCCESS
07-10 19:48:04.127    8137-8137/com.layer.atlas.messenger V/LayerSDK﹕ LayerClientImpl - 2015-07-10T19:48:04.127 EDT : com.layer.sdk.internal.LayerClientImpl.registerAuthenticationListener(LayerClientImpl.java:1889) : Registering LayerAuthenticationListener, 1 listeners registered
07-10 19:48:04.128    8137-8137/com.layer.atlas.messenger V/LayerSDK﹕ LayerClientImpl - 2015-07-10T19:48:04.128 EDT : com.layer.sdk.internal.LayerClientImpl.authenticate(LayerClientImpl.java:1819) : Authenticating
07-10 19:48:04.128    8137-8137/com.layer.atlas.messenger V/LayerSDK﹕ AuthManager - 2015-07-10T19:48:04.128 EDT : com.layer.sdk.internal.utils.statemachine.AuthManager.a(AuthManager.java:224) : Already connected. Trying to authenticate
07-10 19:48:04.196    8137-8681/com.layer.atlas.messenger V/LayerSDK﹕ LayerClientImpl - 2015-07-10T19:48:04.196 EDT : com.layer.sdk.internal.LayerClientImpl.a(LayerClientImpl.java:1139) : Authentication challenge, nonce length: 88
07-10 19:48:04.196    8137-8137/com.layer.atlas.messenger W/AtlasLoginScreen﹕ onAuthenticationChallenge() nonce: ZZKXQbuXQbfqHJgJHboKllb1GKbfcA+ZY3fO5f6pOZg8dLwmZda1b+7hEOp4zCplenURZoIIj1pAo1nyB28klg==
07-10 19:48:04.589    8137-8684/com.layer.atlas.messenger W/DefaultRequestDirector﹕ Authentication error: Unable to respond to any of these challenges: {}
07-10 19:48:04.589    8137-8684/com.layer.atlas.messenger E/HerokuIdentityProvider﹕ Got status 401 when logging in

**Comment by niravPercept** [comment]
I got the same error message when login in using my appID.. Working perfectly when i run application with null appID.

07-23 09:54:12.226  30420-30503/com.layer.atlas.messenger E/HerokuIdentityProvider﹕ Got status 401 when logging in
07-23 09:54:12.226  30420-30503/com.layer.atlas.messenger W/System.err﹕ java.lang.NullPointerException
07-23 09:54:12.226  30420-30503/com.layer.atlas.messenger W/System.err﹕ at com.layer.atlas.messenger.AtlasLoginScreen$3$1.run(AtlasLoginScreen.java:117)
07-23 09:54:12.226  30420-30503/com.layer.atlas.messenger W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
