### ISSUE TITLE
Duplicate <provider> element

### ISSUE THREAD

**Issue by josealfonsomora** [layerhq/Atlas-Android#137]
To use the camera in the app I need to add a <provider> element in manifest, but only one provider is allowed in the same app and Atlas already defined one in its manifes. Merge the manifest overrides the Atlas provider.

I had to check Atlas manifest code to copy the provider name and authority string and use this authority `${applicationId}.com.layer.atlas.provider` in the app

So basically, unless I'm mistaken and there is another way to solve this situation, updating Atlas force us to refactor our providers in the app and if in a future Atlas change its provider will force us again to change the provider

**Comment by milan-milojevic** [comment]
I just encountered the same issue @josealfonsomora . How did you solve it? By merely copying the whole provided and adding it to you main manifest list of already defined providers? Thanks!

**Comment by josealfonsomora** [comment]
Hi @milan-milojevic, what you have to do is change your provider to match the atlas provider changing the authorities to `android:authorities="${applicationId}.com.layer.atlas.provider"` and adding the path `<external-path name="external_files" path="."/>` in your file path.

After that you only have to add the instructions tools:replace="android:authorities" and tools:replace="android:resource" to let gradle merge the manifest.

This is a copy on mine:
```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.com.layer.atlas.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"
                tools:replace="android:resource"/>

</provider>
```

And this is my file_paths.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="my_images"
        path="Android/data/com.plynk.me/files/Pictures" />
    <external-path name="external_files" path="."/>
</paths>
```

**## NOTE**
There is an open PR to fix the problem https://github.com/layerhq/Atlas-Android/pull/140 which basically removes the Atlas provider

**Comment by milan-milojevic** [comment]
Thanks for the very helpful response @josealfonsomora !

**Comment by thecombatwombat** [comment]
@josealfonsomora Thanks for reporting this and for helping out!

@milan-milojevic #140 removes the `FileProvider` from `Atlas-Android`, but that necessitates you implementing one yourself, and supplying the `CameraSender` instance with the `FileProvider`'s authority. 

Once #140 is merged in, we'll have the corresponding changes made to [Atlas-Android-Messenger](https://github.com/layerhq/Atlas-Android-Messenger), so you can see an example implementation there. I'll update this thread with a link to that.

**Comment by thecombatwombat** [comment]
`FileProvider` & `CameraSender` implementation example 
(https://github.com/layerhq/Atlas-Android-Messenger/commit/bff55f86d81740d8c734a95f928fb1e14fbd7b01)

**Comment by milan-milojevic** [comment]
thank you @thecombatwombat ! did the trick!
