### ISSUE TITLE
Mark all conversation as read

### ISSUE THREAD

**Issue by josealfonsomora** [layerhq/Atlas-Android#138]
@smpete @thecombatwombat @sriamar 
Do we have any way to mark all conversation messages as read like Layer IOS in Android?     https://docs.layer.com/api_reference/ios-0.23.0/Classes/LYRConversation.html#/c:objc(cs)LYRConversation(im)markAllMessagesAsRead:

Or do I have to iterate over all conversation messages and mark one by one as read?

Thanks!

**Comment by thecombatwombat** [comment]
@josealfonsomora We're still working on a mark all as read feature, so for now you'll just have to iterate over the conversation messages and mark them as read

**Comment by josealfonsomora** [comment]
Thanks @thecombatwombat 
I think we can close this issue
