### ISSUE TITLE
Chat bubble is empty on receiving end when sending very long messages

### ISSUE THREAD

**Issue by szabolcsarvai** [layerhq/Atlas-Android#142]
On device A type in and send a long message (2800 characters in this case), on device B an empty chat bubble will appear. On device A the message will appear as if it was sent.
Reloading the screen solved the problem.

Any idea?

Thanks!

**Comment by andela-wakinsanmi** [comment]
Hello @szabolcsarvai 

Thanks for dropping this issue, I have tested this. I notice sometimes that the chat bubble appears and later the text shows up.  We will work on this.

**Comment by thecombatwombat** [comment]
This is tracked internally on JIRA as `AND-982`

@szabolcsarvai Thanks for reporting this, we're working on addressing the problem. 
If you have blocking issues, its best to get in touch with us at [our support site](https://support.layer.com). That allows us to track issues better, and hopefully be more responsive as well. 

Thank you!

**Comment by andela-wakinsanmi** [comment]
@szabolcsarvai This has been fixed https://github.com/layerhq/Atlas-Android/pull/183/files

**Comment by szabolcsarvai** [comment]
Hello @andela-wakinsanmi and @thecombatwombat 

Thanks for fixing this issue! 🍻 🍻

Have a nice day!
