### ISSUE TITLE
New Message User list is empty

### ISSUE THREAD

**Issue by ganeshub** [layerhq/Atlas-Android#151]
AtlasAddressBar identitiesFetched is always empty even though I have '2 registered users' in dashboard.
I am using node.js custom identity token issuer in localhost. The created token are valid when checked in the identity token validation tool in Tools settings.

**Comment by ganeshub** [comment]
It lists all the users if I use the Atlas Messenger demo appId.
But It is not working for my own appId.

**Comment by andela-wakinsanmi** [comment]
Hello @ganeshub 

Given user A, you need to follow user B in order for user B to show up in the identitiesFetched.

You have two options to achieve this:

You can use the client api https://docs.layer.com/reference/client_api/identities.out#follow-a-user

or do it on Android https://docs.layer.com/sdk/android/identities#following
