### ISSUE TITLE
Broken avatars in release 0.4.4 for group conversations

### ISSUE THREAD

**Issue by milan-milojevic** [layerhq/Atlas-Android#156]
When you added the possibility to optionally show other participant's avatar in `oneOnOne` conversations, you removed these lines of code:

```
viewHolder.mAvatar.setVisibility(View.VISIBLE);
 viewHolder.mAvatar.setParticipants(message.getSender());
```

from the `else if` statement after `if (oneOnOne)` in `AtlasMessagesAdapter`

I believe those 2 lines of code should have stayed there along with the introduced changes to the `oneOnOne` conversation.

**Comment by thecombatwombat** [comment]
Thanks for reporting this @milan-milojevic . I've got #157 to fix this.
