### ISSUE TITLE
It is posible to have a cell without sender and avatar?

### ISSUE THREAD

**Issue by josealfonsomora** [layerhq/Atlas-Android#158]
I'm trying to create some 'conversation status messages' that are sent by participants, but should be read like messages from the conversation with different style, no sender, no clickable, etc..

I saw in the AtlasMessageAdapter how the cell view is being wrapped by other views that display the avatar and everything I don't want like atlas_message_item_footer or atlas_message_item_me or atlas_message_item_them

Is that posible?

**Comment by thecombatwombat** [comment]
Currently... your best bet would be to fork Atlas to do what you are describing. 

I'll make a note of your request and we'll try and take it into account for future versions.
