### ISSUE TITLE
Location Sender never receives an update

### ISSUE THREAD

**Issue by sergiandreplace** [layerhq/Atlas-Android#159]
I'm using Atlas and the Location Sender.

I've found an erratic behaviour that happens sometimes in a random basis (or at least I haven't find the reason).

When you request to send a location, nothing happens. This happens from time to time, and as far as I can see, once this happens, it will never works for the life of the current activity.

After doing a bit of debug of the LocationSender, these are my findings.

The ```LocationServices.FusedLocationApi.requestLocationUpdates(sGoogleApiClient, r, listener);``` is correctly invoked, but, the  ```onLocationChanged(Location location)`` is never called.

Keep in mind that we saw this issue in different phones and even in the same phone among executions without any kind of setting modification.

Any clue on this?

Thanks!

**Comment by andela-wakinsanmi** [comment]
Hello @sergiandreplace 

Thanks for reaching out to us, I have tried to replicate this issue, the only time nothing happens when I request a Location is when I have my location turned off.

Can you please provide any log which can help us figure out exactly what's happening?

Thanks

**Comment by andela-wakinsanmi** [comment]
Hello,

I am going to close this issue, please reopen it if this still exists.

Thanks

**Comment by sergiandreplace** [comment]
FYI: we updated to last version and the error is not repro anymore
