### ISSUE TITLE
404 Error ehen logging in

### ISSUE THREAD

**Issue by onderix** [layerhq/Atlas-Android#16]
Hi,

I tried to run Atlas android sample with my layer Id but I am getting following error : 

E/AtlasIdentityProvider﹕ Got status 404 [HTTP/1.1 404 Not Found] when logging in. Request: https://layer-identity-provider.herokuapp.com/apps/xxx/atlas_identities login: Ee, nonce: xxx

I am sure my id is correct because it wotks with another sample without any exeption (https://github.com/layerhq/quick-start-android)

What is the problem? How Can I fix this?

Regards

**Comment by jcarrharris** [comment]
Having the same issue.

**Comment by viniciusmo** [comment]
Having the same issue. [2]

**Comment by viniciusmo** [comment]
@blakewatters  @jessedavidson  @mubarak @neonichu @nilgradisnik @segiddins @sjones94549 @sriamar

**Comment by viniciusmo** [comment]
@blakewatters

**Comment by oorlov** [comment]
@viniciusmo @jcarrharris 
Hey guys, have you tried latest version of Atlas from master? (Logging was upgraded about 3 weeks ago)? 
There should be an exception in LogCat. Could you print it here?

**Comment by sjones94549** [comment]
I believe this is because the `atlas_identities` identity provider expects an Atlas app ID.  You would have to use either an Atlas app ID, or replace the identity provider here with one that talks to your backend (or the endpoint from the quickstart app).
