### ISSUE TITLE
Error: Duplicate resources

### ISSUE THREAD

**Issue by hishamdubizzle** [layerhq/Atlas-Android#161]
Dears,
       Thanks for great effort. I face an issue when I upgraded to :

distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
classpath 'com.android.tools.build:gradle:2.4.0-alpha1'
buildToolsVersion '25.0.2'

I face this error when I build my app:
Error: Duplicate resources string/google_crash_reporting_api_key

I use:
 compile('com.layer.atlas:layer-atlas:0.4.5') {
      exclude module: 'recyclerview-v7'
      exclude module: 'design'
      exclude module: 'appcompat'
      exclude group: 'com.google.android.gms', module: 'play-services'
    }

**Comment by hishamdubizzle** [comment]
Dears,
is there any update? it is very important because i need this to enable instant run. without it, every build takes 4 minutes.

**Comment by sriamar** [comment]
Hello,

We are building Messenger on Gradle `3.3` with the `2.4.0-alpha7` plugin on the preview tools, and our build works fine. If you are still facing this issue, please provide us the sample project where you are seeing this issue, and we will take a look.

Thanks
Amar

**Comment by hishamdubizzle** [comment]
Many thanks. I am waiting the team to try it again. for now, we stick to
old gradle plugin as we are afraid of introducing any new issues now.

**Comment by sriamar** [comment]
Thanks! Please do let us know if you run into issues here. You can email support<at>layer.com for faster response.
