### ISSUE TITLE
Two different users with same conversation URL

### ISSUE THREAD

**Issue by outlander24** [layerhq/Atlas-Android#187]
I am facing an issue where in two different users receive the same chat notification due to which a user can see other users personal chat. What can be the possible cause of the error? Can `options.alternateFcmSenderId("alternate_sender_ID")` cause this? I followed the init process as described [here](https://docs.layer.com/sdk/android/push)

**Comment by sriamar** [comment]
Hi @outlander24 

These issues are only for Atlas-Android. For other issues, please follow the instructions here to capture logs, and contact support@layer.com

Thanks
Amar
