### ISSUE TITLE
Content Type of image uploaded is `image/jpeg+preview`

### ISSUE THREAD

**Issue by adin234** [layerhq/Atlas-Android#191]
Why is it that when we upload an image using the `ThreePartImageUtils`, the content-type from google is `image/jpeg+preview`. this causes a problem in the `react-sdk`

![image](https://cloud.githubusercontent.com/assets/3828145/26771164/19d46508-49ef-11e7-955e-a82548a6c53e.png)

```
accept-ranges:bytes
access-control-allow-origin:*
access-control-expose-headers:*, Content-Length, Date, Server, Transfer-Encoding, X-GUploader-UploadID, X-Google-GFE-Backend-Request-Cost, X-Google-GFE-Cloud-Project-Number, X-Google-GFE-Load-Report, X-Google-Trace
alt-svc:quic=":443"; ma=2592000; v="38,37,36,35"
cache-control:private, max-age=0
content-length:8924
content-type:image/jpeg+preview
date:Mon, 05 Jun 2017 05:00:54 GMT
etag:"e6519564fe16447b1d4bc42c2a030efa"
expires:Mon, 05 Jun 2017 05:00:54 GMT
last-modified:Mon, 05 Jun 2017 04:08:44 GMT
server:UploadServer
status:200
x-goog-generation:<some values>
x-goog-hash:<some values>
x-goog-hash:<some values>
x-goog-metageneration:<some values>
x-goog-storage-class:<some values>
x-goog-stored-content-encoding:identity
x-goog-stored-content-length:8924
x-guploader-uploadid:<some values>
```

the react-sdk isn't able to render the image i assume because of the content-type

**Comment by sriamar** [comment]
Hi @adin234 

That is the format for preview image in ThreePartImageUtils. I am not sure what `react-sdk` you are referring to. In general, other sdk should implement support for mime types as defined here for them to support messages generated using ThreePartImageUtils.

I am closing this issue as support is provided via support@layer.com. Please contact that email for support questions.

Thanks,
Amar
