### ISSUE TITLE
Docs appear to be wrong

### ISSUE THREAD

**Issue by rajohns08** [layerhq/Atlas-Android#200]
https://docs.layer.com/sdk/android/authentication#deauthenticating

> Deauthenticating will delete locally stored data (which includes the user’s conversations and messages). **In addition, the Layer client will be disconnected. If you want to authenticate another user, you’ll have to re-connect the Layer client.**

When I call `layerClient.deauthenticate()`, my `onConnectionDisconnected` callback is never called, and I don't have to call `.connect()` again before authenticating the user again.

**Comment by sriamar** [comment]
Thanks for pointing out. We will get the document fixed. 

Your observation is correct. `deauthenticate()` doesn't disconnect.
