### ISSUE TITLE
Change avatar placeholder

### ISSUE THREAD

**Issue by arielbts** [layerhq/Atlas-Android#201]
Hi everyone!

If possible to change the place holder for the avatar? I want to show the initials of the user´s name instead of the actual holder (the tiny person).

Is it possible do that using the atlas components? Or I need to create my own avatar class?

**Comment by sriamar** [comment]
Atlas's default is to draw initials if the user's image was not specified. The tiny person might be the one you populated with Identity.

https://github.com/layerhq/Atlas-Android/blob/master/layer-atlas/src/main/java/com/layer/atlas/AtlasAvatar.java#L329

You can see where that bitmap is coming from in a debugger.

Hope that helps,

Thanks
Amar
