### ISSUE TITLE
Avatar Text TypeFont

### ISSUE THREAD

**Issue by arielbts** [layerhq/Atlas-Android#202]
Is it possible to change the type font of the avatars? I need to use my own .ttf fonts. On the atlas styles, there is an avatarTextTypeface attribute but i can not set the font there.
Is there any way to do that?

**Comment by thecombatwombat** [comment]
@arielbts Currently your best bet is to fork the repo. We _are_ working on a bunch of changes to better support customizations and styling, but I don't yet have a timeline that I could give you.
