### ISSUE TITLE
CameraSender/GallerySender update documentation

### ISSUE THREAD

**Issue by rajohns08** [layerhq/Atlas-Android#210]
I think it would be a good idea to call out in the documentation somewhere that `onActivityResult` and `onRequestPermissionsResult` should be implemented in your message list activity passing the info through to your messageComposer. I spent a few hours trying to figure out why attaching images wasn't working in my chat. Finally found these overrides shown in the sample app source code.

**Comment by csbrandt** [comment]
For technical assistance please reach out to us via [support.layer.com](https://support.layer.com/).
