### ISSUE TITLE
Show preview

### ISSUE THREAD

**Issue by arielbts** [layerhq/Atlas-Android#212]
Hi everyone!

I was wondering if it is possible to show a like for example an image preview on the AtlasMessageComposer before send it.

I was digging a little bit but i could not find anything related with that.

**Comment by thecombatwombat** [comment]
We currently don't have any support for that. 
Feel free to make a pull request in case you think it would be useful to other developers as well! We'd love to see contributions and will try our best to include them/the ideas in there going forward.
