### ISSUE TITLE
Presence Status

### ISSUE THREAD

**Issue by josealfonsomora** [layerhq/Atlas-Android#213]
After update Atlas library, AtlasAvatar has by default a `dot` to show the user presence.

Is there a way to not show the dot at all? I saw in the code that the dot is printed unless PresenceStatus is null, but by default PresenceStatus is INVISIBLE that curiously is not INVISIBLE :-D

**Comment by poorna204** [comment]
mAvatarImageView.setShouldShowPresence(false);

**Comment by josealfonsomora** [comment]
Thanks @poorna204 
I wont be able to modify this attribute if I'm using AtlasConversationsRecyclerView right?

**Comment by rohitramkumar308** [comment]
There is a Convenience method in the recycler view:
```
  public AtlasMessagesRecyclerView setShouldShowAvatarPresence(boolean shouldShowAvatarPresence) {
        mAdapter.setShouldShowAvatarPresence(shouldShowAvatarPresence);
        return this;
    }
```

**Comment by rohitramkumar308** [comment]
Submitted a PR https://github.com/layerhq/Atlas-Android/pull/216

**Comment by thecombatwombat** [comment]
PR #216 has been merged
