### ISSUE TITLE
TransformException with Atlas 0.4.9 and 0.4.10

### ISSUE THREAD

**Issue by josealfonsomora** [layerhq/Atlas-Android#214]
Updating Atlas library to 0.4.9 or 0.4.10 throws this exception in compile time.

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/gcm/PendingCallback$1.class

There is something new in 0.4.9 that is conflicting with my libraries?
How can I solve it?

I tried different things like exclude firebase or com.google.android.gms from Atlas and Layer, but still error :-(

```
compile ("com.layer.atlas:layer-atlas:${appLibs.ATLAS_VERSION}"){
        exclude group: 'com.google.android.gms'
        exclude group: 'com.android.support'
        exclude group: 'com.squareup.picasso', module: 'picasso'
        exclude group: 'org.slf4j', module: 'slf4j-nop'
}
```

**Comment by cristian-calugar** [comment]
Ji Josef,

We get the same error. 
Have you fund any solution?

Thanks,
Cristi.

**Comment by cristian-calugar** [comment]
Hi @sriamar,

Is there a workaround for this issue?

Thanks,
Cristi.

**Comment by rohitramkumar308** [comment]
I just updated my version from 0.4.6 to 0.4.10 and did not see an exception. This is what I have:

```
compile('com.layer.atlas:layer-atlas:0.4.9') {
        exclude group: 'com.google.android.gms', module: 'play-services-location'
    }
```

**Comment by thecombatwombat** [comment]
@josealfonsomora please update to the latest version of Atlas, which is currently `0.4.15`

That should fix this problem
