### ISSUE TITLE
Is there any way to set an 'empty' message for conversation without any messages yet?

### ISSUE THREAD

**Issue by rajohns08** [layerhq/Atlas-Android#221]
I'd like to show a message like "Start a conversation with John. Send your first message." if the conversation doesn't have any messages. Does the `AtlasMessagesRecyclerView` or anything else have any kind of `setEmptyMessage` method or something?

**Comment by csbrandt** [comment]
For technical assistance please reach out to us via [support.layer.com](https://support.layer.com/).

**Comment by timusus** [comment]
I would also like to know how to achieve this.

Some combination of a `LayerChangeEventListener` listening for new messages, and a query to see if there are any active conversations?

**Comment by andela-wakinsanmi** [comment]
Hello @timusus 

We are working on a main version of Atlas-Android, we will ship this feature along side with it. For now, a simple work around will be to create an object of `RecyclerView.AdapterDataObserver` and register it on the Adapter, call onChanged on the dataObserver. That way, you can display an EmptyView and when there is data remove it.

Please let me know if this is still an issue.

Thanks
