### ISSUE TITLE
UI element for Announcements.

### ISSUE THREAD

**Issue by rohitramkumar308** [layerhq/Atlas-Android#235]
Is there any UI element for announcements ? Basically query all announcements in recyclerview and when the user taps on one, display the details.

**Comment by csbrandt** [comment]
For technical assistance please reach out to us via [support.layer.com](https://support.layer.com/).

**Comment by IHNEL** [comment]
Very bad in support. Your support.layer.com is not friendly enough for developers. Why don't answer here so everyone can see and follow up?
