### ISSUE TITLE
Locally created conversation does not show up in AtlasConversationsRecyclerView

### ISSUE THREAD

**Issue by cassioso** [layerhq/Atlas-Android#241]
Hi,

I'm using `AtlasConversationsRecyclerView` to show the list of conversations in my Android app.
Before showing the conversation list, I'm fetching a custom list of layer user ids from our backend and, for each id, I'm creating a new conversation using `newConversationWithUserIds`.
LayerSDK prints some debug saying that the conversation is being successfully created:

> (...)com.layer.sdk.internal.lsdkk.k.e(Log.java:465) : Creating new Conversation, Id: layer:///conversations/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

However, when displaying the conversation list, it does not show the locally created conversations.

This code is already in production since a few months ago and only recently users start to complain about not seeing some conversations that should be listed.

When the conversations are created from the Web Client or backend, then it is normally showing up on the mobile conversation list.

We tried to change the conversation creation for different moments but none of these approaches are working:

- Just after connected and if authenticated (onConnectionConnected)
- Just after layer authentication (onAuthenticated);
- Just after sync (onAfterSync)

We've been using Atlas-Android version 0.4.10 and we verified the same porblem when using the latest version (0.4.12).

**Comment by csbrandt** [comment]
For technical assistance please reach out to us via [support.layer.com](https://support.layer.com/).
