### ISSUE TITLE
Cannot resolve LayerFcmService and PushNotificationPayload

### ISSUE THREAD

**Issue by atrindam** [layerhq/Atlas-Android#245]
In manifest.xml file, LayerFcmService is not recognized. It's displayed in red color. Also 
import com.layer.sdk.messaging.PushNotificationPayload shows PushNotificationPayload in red

**Comment by timusus** [comment]
@atrindam there's not much information here. 'Displayed in red' could mean any number of things. Do you get a compilation error when you try to build the app? 

>import com.layer.sdk.messaging.PushNotificationPayload shows PushNotificationPayload

Where are you importing `PushNotificationPayload`? Can you post some code?

**Comment by atrindam** [comment]
Hi Tim,
I have another issue.When I download the zip file for Atlas-Messenger from
-"https://github.com/layerhq/Atlas-Android-Messenger". and try to run it on
android studio, I get the following error:

Error:Project :app declares a dependency from configuration 'compile' to
configuration 'default' which is not declared in the descriptor for project
:layer-atlas.

Also the file Atlas-Android is empty.


Regards,

*Arindam Dhar*
*Head of Sponsorship*
*Coalescence '16*
*BITS Pilani, K. K. Birla Goa Campus*
atarindam@gmail.com | +91 91309 76096

**Comment by timusus** [comment]
@atrindam I don't work for Layer, so you should probably address your question to them.

In any case, your second issue is not at all related to the first, you should create a separate issue. Further, this is an Android/gradle dependency issue, and not strictly related to Layer.

>When I download the zip file for Atlas-Messenger from
-"https://github.com/layerhq/Atlas-Android-Messenger". and try to run it on
android studio, I get the following error

You haven't posted any code (like your `build.gradle` file), or shown what directory you've extracted the contents of the Atlas zip into. You'll need to provide much clearer and more concise information if you're actually looking for some help.

A quick Google search yields the following:
https://stackoverflow.com/questions/42929841/app-declares-a-dependency-from-configuration-compile-to-configuration-default

**Comment by atrindam** [comment]
Hi Tim,
True that this issue is a different one. I'll be creating a new issue with
the code and error logs included. Thanks for your help
