### ISSUE TITLE
Building Custom Message Cells

### ISSUE THREAD

**Issue by bennettl** [layerhq/Atlas-Android#261]
Hello,

I don't believe there's documentation on how to construct custom message UI cells within Layer Atlas for Android. I tried visiting https://docs.layer.com/sdk/android/ui_customization , but it leads to a 404 page.

**Comment by thecombatwombat** [comment]
@bennettl not sure where you got that link from, but those are SDK docs and contain nothing about Atlas. 
I'd start here:
https://github.com/layerhq/Atlas-Android/blob/master/README.md

**Comment by bennettl** [comment]
Thanks for the clarification, I did check that documentation and couldn't find a mention of building a custom message cell. Looking through the Atlas Messenger sample app, it seems that I need to subclass AtlasCellFactory, but not entirely sure how to go about building a custom cell with a  horizontal scrollable list (recycler view).
