### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by sjones94549** [layerhq/Atlas-Android#29]
Add support for rendering and sending animated GIFs:
- GifCellFactory
- GifSender

**Comment by PratapOdedara** [comment]
I can do it but for that i have to add new 17 classes and also have to add some thirdpary libraries as you there is no support for gif in android

**Comment by sriamar** [comment]
Hello,

This feature request is internally tracked with id PROD-155. If you have any questions regarding this, please reach out to Layer Support via support.layer.com and mention the issue number.

Thanks,
Amar
