### ISSUE TITLE
Maven

### ISSUE THREAD

**Issue by Leland-Takamine** [layerhq/Atlas-Android#3]
Any plans to deploy this to Maven Central?

**Comment by nick-at-humin** [comment]
:+1: For either deployment to Maven Central, or a private repo managed in Github.

**Comment by jitpack-io** [comment]
Hi! In the meantime you could get it as a maven/gradle dependency from https://jitpack.io/#layerhq/Atlas-Android/0.9.9

**Comment by sjones94549** [comment]
we'll get it published once this repo as out of beta (possibly before)
