### ISSUE TITLE
Add video support

### ISSUE THREAD

**Issue by sjones94549** [layerhq/Atlas-Android#30]
Add ability to render and send videos:
- VideoCellFactory
- VideoSender

**Comment by PratapOdedara** [comment]
Hey @sjones94549 Did you get any sucess in video sender and videocellfactory if got anything then pleae help me to achive video sending

**Comment by PratapOdedara** [comment]
Hey Friends I have Sucessfully created VideoCellFActory, and video sender and also tested it and it is working fine

**Comment by sriamar** [comment]
@PratapOdedara : Please create a pull request on github with your changes. We will take a look. https://help.github.com/articles/using-pull-requests/

**Comment by jindalbitazuga** [comment]
Hi Sriamar, any update on Video Sender feature ? Saw on the main page that Layer is actively integrating the feature for Video support. But could not find any branch or pull request for the same.

**Comment by sriamar** [comment]
No, we are not working on that right now. We are focused on other things. So, this is not in our immediate backlog. 

If you have a need, and implement it, please do send a PR and we will take a look.

**Comment by sriamar** [comment]
Hello,

This feature request  is internally tracked as  `PRODUCT-156`. If you have any questions regarding this, please reach out to Layer Support via https://support.layer.com/ and mention the internal tracking id.

Thanks
Amar

**Comment by rekhaagarwal** [comment]
Hello @sriamar 
Is this feature(video support) is added in latest release ?
