### ISSUE TITLE
Automated UI Tests

### ISSUE THREAD

**Issue by sjones94549** [layerhq/Atlas-Android#31]
Create test suite for UI elements

**Comment by alexfdz** [comment]
@smpete you are quite an active committer in this repo. Do you know if there is any plan to add any kind of test suite (unit or UI automated testing)

**Comment by smpete** [comment]
Thanks for the suggestion @alexfdz. That is definitely something we want to do but are currently lacking resources for it given our current priorities. We hope to have that sorted out soon!

**Comment by sriamar** [comment]
Fyi : @thecombatwombat

**Comment by thecombatwombat** [comment]
Currently working on this... should have the basics up and running soon. We'll be adding more support and tests going forward.

**Comment by thecombatwombat** [comment]
Tracked in JIRA as `AND-410`
