### ISSUE TITLE
beforeSend removed

### ISSUE THREAD

**Issue by bryant1410** [layerhq/Atlas-Android#33]
Why the `setListener` and `beforeSend` event were removed from [AtlasMessageComposer](https://github.com/layerhq/Atlas-Android/blob/master/layer-atlas/src/main/java/com/layer/atlas/AtlasMessageComposer.java)?

**Comment by sjones94549** [comment]
Text messages are now sent with [TextSender](https://github.com/layerhq/Atlas-Android/blob/master/layer-atlas/src/main/java/com/layer/atlas/messagetypes/text/TextSender.java), which also handles notifications.

Set it on the AtlasMessageComposer like this:
https://github.com/layerhq/Atlas-Android-Messenger/blob/master/app/src/main/java/com/layer/messenger/MessagesListActivity.java#L196

**Comment by bryant1410** [comment]
Yeah but it would be cool to have a listener when messages are sent too

**Comment by sjones94549** [comment]
Ah, got it.  Yeah, you'd want a way to know about the Message created by the MessageSender so you can monitor status changes and the like.  Something like this, on `MessageSender`:

``` java
/**
 * Callback alerts external classes of MessageSender events.
 */
public interface Callback {
    /**
     * Called when this MessageSender creates a new Message and queues the Message for sending.
     *
     * @param sender  The MessageSender reporting Message creation.
     * @param message The new Message created.
     */
    void onMessageCreated(MessageSender sender, Message message);
}
```

**Comment by bryant1410** [comment]
Yeah, something like that! :smile:

**Comment by sjones94549** [comment]
I'm going to experiment with a hybrid in Atlas/Messenger:

``` java
    /**
     * Callback alerts external classes of MessageSender events.
     */
    public interface Callback {
        /**
         * Called when this MessageSender creates a new Message, before queuing the Message for
         * sending.  Options can be set on the Message at this time.  Return `true` to continue with
         * sending the Message, or `false` to prevent sending.  If sending continues, track updates
         * to the Message with a LayerChangeEventListener.
         *
         * @param sender  The MessageSender reporting Message creation.
         * @param message The new Message created.
         * @see com.layer.sdk.messaging.Message
         * @see com.layer.sdk.listeners.LayerChangeEventListener
         */
        boolean onBeforeSend(MessageSender sender, Message message);
    }
```

**Comment by bryant1410** [comment]
:+1:

**Comment by sjones94549** [comment]
PR #34 opened.
