### ISSUE TITLE
Delete Conversation

### ISSUE THREAD

**Issue by willyanto** [layerhq/Atlas-Android#4]
Can you guys give an example for delete conversation? one user delete conversation without delete in other user.. This is done by DeletionMode LOCAL. But I want when user reinstall the apps (relogin/reauthentication), deleted conversation not show again.. Thx

**Comment by sjones94549** [comment]
We will be implementing this in an upcoming SDK release.  At present, you can either delete for all users, or on your current device (until you log out and back in).
