### ISSUE TITLE
Clicking on an image a few times results in OOM

### ISSUE THREAD

**Issue by snooplsm** [layerhq/Atlas-Android#44]
https://www.amazon.com/clouddrive/share/BDA13O80UyomIfAGxIKw1a8wvcI46qLdWouVeMlcaGg?v=grid&ref_=cd_ph_share_link_copy

Clicking on an image a few times results in Out of Memory Exception

01-11 14:17:01.816  2524  2715 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
01-11 14:17:01.816  2524  2715 E AndroidRuntime: Process: com.playdraft.draft.staging.debug, PID: 2524
01-11 14:17:01.816  2524  2715 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at android.os.AsyncTask$3.done(AsyncTask.java:309)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:818)
01-11 14:17:01.816  2524  2715 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 35808268 byte allocation with 1908464 free bytes and 1863KB until OOM
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:649)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at com.layer.atlas.util.imagepopup.MessagePartDecoder.decode(MessagePartDecoder.java:45)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1558)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1533)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at android.os.AsyncTask$2.call(AsyncTask.java:295)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-11 14:17:01.816  2524  2715 E AndroidRuntime:    ... 4 more

**Comment by snooplsm** [comment]
I think in onDestroy of the AtlasImagePopupActivity you should this:

    @Override protected void onDestroy() {
        super.onDestroy();
        if(mImageView!=null) {
            mImageView.recycle();
        }
    }

**Comment by andela-wakinsanmi** [comment]
Hello @snooplsm 

Thank you so much for raising this issue and we are sorry for replying late. I have tried to reproduce the issue but couldn't. I will close this issue right now, please kindly reopen it if it's still reoccurring.
Thanks.
