### ISSUE TITLE
Missing timestamp for first message

### ISSUE THREAD

**Issue by cshah3** [layerhq/Atlas-Android#45]
There's no timestamp visible for the first message in a conversation.

**Comment by sjones94549** [comment]
This is by design; here's the logic that does that, if you'd like to change it:
https://github.com/layerhq/Atlas-Android/blob/master/layer-atlas/src/main/java/com/layer/atlas/adapters/AtlasMessagesAdapter.java#L281

**Comment by cshah3** [comment]
Thanks!
