### ISSUE TITLE
Is it possible to style the "read", etc, status text?

### ISSUE THREAD

**Issue by pklada** [layerhq/Atlas-Android#46]
I'd like to be able to style this text

![image](https://cloud.githubusercontent.com/assets/1474231/12567039/d31d5200-c371-11e5-9e34-824faf17ad9e.png)

I looked at the source and didn't see anything immediately obvious referencing this. Am I overlooking something or is it not stylable at the moment?

**Comment by sjones94549** [comment]
It's not yet exposed through a custom attribute or similar; you could make a PR for that though, it'd be similar to `myTextColor` etc:
https://github.com/layerhq/Atlas-Android/blob/master/layer-atlas/src/main/res/values/atlas-attrs.xml#L57
