### ISSUE TITLE
Camera permission and Read external storage permission not needed when using intents

### ISSUE THREAD

**Issue by cristian-calugar** [layerhq/Atlas-Android#50]
Hi,

In the last update you changed the CameraSender and GalerySender to handle permissions request for Camera, respectively for reading external storage. In fact when using intents like ACTION_IMAGE_CAPTURE and ACTION_PICK you do not need to request these permissions. Another app is opened and that app needs to have the permissions not our app. 

The big problem is that now our app needs to request these permissions in order to work. Where before these changes it worked fine without asking these permissions. Please revert.

More info here:

https://www.youtube.com/watch?v=5xVh-7ywKpE&list=PLWz5rJ2EKKc_Tt7q77qwyKRgytF1RzRx8&index=9

Thanks,
Cristi.

**Comment by sjones94549** [comment]
Hey Cristi, I'll double check that.  During testing, without the CAMERA permission, on a Nexus 5X running Marshmallow, the app crashed noting that the CAMERA permission was not present.  Maybe there's something I missed.

**Comment by sjones94549** [comment]
Indeed, please see:
http://developer.android.com/reference/android/provider/MediaStore.html#ACTION_IMAGE_CAPTURE

```
Note: if you app targets M and above and declares as using the
CAMERA permission which is not granted, then attempting to use
this action will result in a SecurityException.
```

If we targeted an API less than Marshmallow, we could remove the CAMERA permission, but dynamic permissions are better for users, so we'd prefer to keep the target where it is.  If you would like to change the target for your own app, feel free to fork Atlas.  Closing for now.

**Comment by sjones94549** [comment]
I spoke too soon -- the key is to not declare the CAMERA permission in the manifest.  Without it declared, the CameraSender works fine.  I'll fix this; thanks for bringing it to our attention!
