### ISSUE TITLE
Add image menu

### ISSUE THREAD

**Issue by VersanM** [layerhq/Atlas-Android#54]
If the user opens the menu for sending an image from gallery or camera he can't close the menu. If he opens the menu and then he wants to write a message and taps the text editor and the keyboard opens, the menu remains opened overlapping the keyboard (screenshots attached). Even if he taps outside the menu it doesn't close.
![layer_issue_1](https://cloud.githubusercontent.com/assets/11414087/13046319/cc0097be-d3e0-11e5-86e6-d3da15f77e3b.png)
![layer_issue_2](https://cloud.githubusercontent.com/assets/11414087/13046318/cc002f7c-d3e0-11e5-8421-a2b41c0a709f.png)

Issue reproduced on Samsung galaxy S6 with Android 5.1.1, Samsung A3 with Android 5.0.2 and HTC One mini 2 with Android 4.4.2. It does'n reproduce on Nexus 5 with Android 6.

**Comment by sjones94549** [comment]
Thanks for the device info; we'll check.  Feel free to try fixing too and submit a PR.

**Comment by mnr-moustafa** [comment]
Any suggestions please?

**Comment by andela-wakinsanmi** [comment]
Hello @VersanM 

I have tried replicating this issue but I can't reproduce it. Please let me know if this is still an issue.

Thanks

**Comment by VersanM** [comment]
I cannot reproduce this issue anymore. I have tried on different devices with different Android OS version and everything seems to work fine. 
I think this issues can be closed!
