### ISSUE TITLE
Participant.getId() conflicts with ORMs

### ISSUE THREAD

**Issue by jeffdgr8** [layerhq/Atlas-Android#67]
We're using greenDAO ORM for abstracting the users in our database as objects. The generated entity classes define the method `getId()` with a Long return type. This is the local database primary key ID for these entities. This conflicts with the `getId()` with a `String` return type defined in the `com.layer.atlas.provider.Participant` interface, which would make sense for our User objects to implement directly. Can this method be renamed to something that won't conflict with ORMs? Maybe `getLayerId()`?

**Comment by andela-wakinsanmi** [comment]
The Participant interface has been removed and replaced with the Identity feature in Layer sdk

https://docs.layer.com/sdk/android/identities
