### ISSUE TITLE
Should decouple Atlas from Picasso

### ISSUE THREAD

**Issue by rockerhieu** [layerhq/Atlas-Android#68]
There are several image loaders out there and you should let everyone free to choose the one that is suite to them.

**Comment by nkleban** [comment]
I agree. We are using Glide in every project, and we are forced to add Picasso dependency just for Atlas.

**Comment by thecombatwombat** [comment]
@rockerhieu, @nkleban thanks for bringing this to our attention. 
You make a valid point, and we'd like to be able to come to a solution wrt this. I don't have a timeline for you yet though. 

We're tracking this internally as AND-979. 

If you're experiencing blocking issues, please use [our support site](https://support.layer.com/) to get in touch with us. That should allow us to be more responsive as well. 

Thank you!
