### ISSUE TITLE
Add an optional header view to AtlasMessagesRecyclerView

### ISSUE THREAD

**Issue by abdyer** [layerhq/Atlas-Android#73]
Since `AtlasMessagesRecyclerView` sets its own adapter, there is currently no straightforward way to add a header view to the message list. The header view would be useful for showing a welcome message or anything else that needs to scroll with the messages in the `RecyclerView`.

**Comment by smpete** [comment]
Tracked internally with issue APPS-2426

**Comment by sriamar** [comment]
Hello,

I am closing the public issue. If you have any questions regarding this, please contact Layer Support via https://support.layer.com/ and mention the internal issue id APPS-2426

Thanks
Amar
