### ISSUE TITLE
Portrait photos are rotated 90º counter clockwise in conversations

### ISSUE THREAD

**Issue by jfrumar** [layerhq/Atlas-Android#8]
When I post photos from my Samsung S5, the images are rotated 90 degrees counter clockwise when I shoot them in portrait mode. If I shoot them landscape style then they are appearing correctly.

**Comment by 3rdstonejubin** [comment]
The culprit maybe Samsung ROM. There are plenty talk on it such as http://stackoverflow.com/questions/13430895/capture-photo-rotate-90-degree-in-samsung-mobile

**Comment by jfrumar** [comment]
Thanks for the lead. You may be right - I've noticed similar behavior in my Google hangouts chat client on the S5. Seems weird that Google has this bug too on such a popular smartphone.
