### ISSUE TITLE
We should add functionality to send contact in atlas-android

### ISSUE THREAD

**Issue by PratapOdedara** [layerhq/Atlas-Android#86]
We should add functionality to send contact in atlas-android it would be great enhancement in library

**Comment by sriamar** [comment]
Hi @PratapOdedara 

Thanks for mentioning this. We are always looking for ways to improve Atlas. I have created an internal item to track this [PROD-154] . If you have any questions regarding this item, please reach out to Layer Support via https://support.layer.com/hc/en-us and somebody will follow-up.

Thanks
Amar
