### ISSUE TITLE
Call to getMessagePreview in custom message factory, not being called.

### ISSUE THREAD

**Issue by cpiggott** [layerhq/Atlas-Android#87]
I recently created a custom message factory for messages I send from my server. 

I am able to display the messages as I need in a chat, but the getMessagePreview(Context context, Message message) is not being called when a preview is needed for the message. 

Instead of the string I return from getMessagePreview, it displays the byte size of the message with the MIME type.

Any idea on what the issue may be?

**Comment by andela-wakinsanmi** [comment]
Hello @cpiggott 

We are sorry for the late reply, please ensure you register your custom cell factory in the ConversationListActivity. It seems like your getMessagePreview is using the GenericCellFactory getMessagePreview.

**Comment by sriamar** [comment]
Hello,

Here is the PR that included support for this. You could look through that too see how things are handled end-to-end. https://github.com/layerhq/Atlas-Android/pull/124

Thanks
Amar
