### ISSUE TITLE
Mocking camera intent for testing purpose returns image not found error.

### ISSUE THREAD

**Issue by prabintim** [layerhq/Atlas-Android#88]
This is a help-needed post rather than an issue. 

I am trying to mock camera intent to send image during chat using layerhq/Atlas-Andorid. The following piece of code for mocking camera intent using espresso works fine, except on Atlas which throws file does not exist error (reason explained below).

```
Bundle bundle = new Bundle();
Bitmap x = BitmapFactory.decodeResource(intentsRule.getActivity().getResources(), R.drawable.accolade_avatar);
bundle.putParcelable("data", x);
Intent result = new Intent();
result.putExtras(bundle);
intending(hasAction(MediaStore.ACTION_IMAGE_CAPTURE)).respondWith(new Instrumentation.ActivityResult(Activity.RESULT_OK, result));
clickItem(MessagePage.attachmentButton);
clickItem(MessagePage.cameraButton);
```

Here is the layer-atlas code for camera intent.

```
private void startCameraIntent(Activity activity) {
    String fileName = "cameraOutput" + System.currentTimeMillis() + ".jpg";
    File file = new File(getContext().getExternalFilesDir(android.os.Environment.DIRECTORY_PICTURES), fileName);
    mPhotoFilePath.set(file.getAbsolutePath());
    Intent cameraIntent = new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE);
    final Uri outputUri = Uri.fromFile(file);
    cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT, outputUri);
    activity.startActivityForResult(cameraIntent, ACTIVITY_REQUEST_CODE);
}
```

The problem is on line
`mPhotoFilePath.set(file.getAbsolutePath());`'

I need to set it to some pre-existing file path like
`mPhotoFilePath.set("/storage/DCIM/camera/image.jpg");`

I cannot modify layer-atlas code. Any help would be appreciated.

**Comment by andela-wakinsanmi** [comment]
Hello @prabintim 

We are sorry for the reply. I think you may want to take a look at IntentTestRule which allows you stub and validate intent. https://developer.android.com/reference/android/support/test/espresso/intent/rule/IntentsTestRule.html
