### ISSUE TITLE
Mocking rest api calls by changing layer baseurl to localhost?

### ISSUE THREAD

**Issue by prabintim** [layerhq/Atlas-Android#89]
Hello,
I am trying to mock web service calls in layer via Android app. For mocking, I am using mockwebserver library. The library requires me to substitute the baseurl of layer (something like https://api.layer.com) to 'localhost'. In our app, we need not define baseurl since it is embedded in the layer sdk itself. So, my question is, is there something like LayerAtlasUtil.setBaseUrl('localhost')?

If you have other recommended way to mock, I would love to know more about it.

**Comment by andela-wakinsanmi** [comment]
Hello @prabintim 

Are you trying to mock the IdentityTokenRequest, can you please provide the servers call you are trying to mock?

**Comment by andela-wakinsanmi** [comment]
Hello,

I am closing this issue now, please reopen it if it's still relevant.

Thanks
