### ISSUE TITLE
Graphic bug , cell cut

### ISSUE THREAD

**Issue by samy-baili** [layerhq/Atlas-Android#93]
Android N Nexus 5x

`compile 'com.layer.sdk:layer-sdk:0.21.2'`
`compile 'org.slf4j:slf4j-nop:1.5.8'`
`compile 'com.layer.atlas:layer-atlas:0.2.10'`

![screenshot_20160701-111927](https://cloud.githubusercontent.com/assets/11545612/16517480/e318aef6-3f7d-11e6-949b-5e515bd26f5a.png)

**Comment by andela-wakinsanmi** [comment]
Hello @samy-baili 

We are sorry for the late reply. Can you please provide more details. I am going to close this now, please reopen it if it's still an issue.

Thanks
