### ISSUE TITLE
Off By One Error

### ISSUE THREAD

**Issue by JeffRegan** [layerhq/Atlas-Android#98]
I think there's an off by one error calculating whether or not to call `onMessageAppend` in the `onQueryItemRangeInserted` in `AtlasMessagesAdapter`.

I think it should be something like this:

```
@Override
public void onQueryItemRangeInserted(RecyclerViewController controller, int positionStart, int itemCount)
{
    mFooterPosition += itemCount;
    updateReceipts();
    notifyItemRangeInserted(positionStart, itemCount);
    int positionEnd = positionStart + itemCount;
    if (mAppendListener != null && positionEnd == getItemCount())
    {
        mAppendListener.onMessageAppend(this, getItem(positionEnd - 1));
    }
}
```

**Comment by andela-wakinsanmi** [comment]
Thanks @JeffRegan 

Thanks for raising this issue. I don't think there is any off by one error. I will close this issue now, if you notice any bug please reopen the issue.
